name: jwizard

services:
  jwizard-vault:
    container_name: jwizard-vault
    image: milosz08/vault-dev:latest
    ports:
      - '${JWIZARD_VAULT_PORT}:8200'
    environment:
      VAULT_AUTO_INIT_ROOT_TOKEN: ${JWIZARD_VAULT_ROOT_TOKEN}
      VAULT_AUTO_INIT_KV_ENGINE: jwizard
      # KV storages
      KV_STORAGE_NORMAL_0: common
      KV_STORAGE_NORMAL_1: landing-page
      KV_STORAGE_NORMAL_2: api
      KV_STORAGE_NORMAL_3: core-instance/0 # 1 instance
      KV_STORAGE_NORMAL_4: core-instance/1 # 2 instance
      KV_STORAGE_NORMAL_5: audio-node/0
      KV_STORAGE_NORMAL_6: audio-node/1
      # common
      V_MYSQL_HOST_0: localhost:${JWIZARD_MYSQL_PORT}
      V_MYSQL_DB_NAME_0: ${JWIZARD_MYSQL_DB_NAME}
      V_MYSQL_USERNAME_0: ${JWIZARD_MYSQL_USERNAME}
      V_MYSQL_PASSWORD_0: ${JWIZARD_MYSQL_PASSWORD}
      # landing page
      V_SERVER_PORT_1: ${JWIZARD_LANDING_PAGE_PORT}
      # api
      V_DISCORD_OAUTH_APP_ID_2: ${JWIZARD_DISCORD_OAUTH_APP_ID}
      V_DISCORD_OAUTH_SECRET_2: ${JWIZARD_DISCORD_OAUTH_SECRET}
      V_GITHUB_TOKEN_2: ${JWIZARD_GITHUB_TOKEN}
      V_AES_SECRET_KEY_2: ${JWIZARD_AES_SECRET_KEY}
      V_GEOLOCATION_API_KEY_2: ${JWIZARD_GEOLOCATION_API_KEY}
      V_XMS_JAVA_2: 256m
      V_XMX_JAVA_2: 256m
      V_SERVER_PORT_2: ${JWIZARD_API_PORT}
      # core-instance/0
      V_JDA_SECRET_3: ${JWIZARD_JDA_SECRET_1_INSTANCE}
      V_JDA_INSTANCE_PREFIX_3: 1
      V_JDA_PRIMARY_COLOR_3: '#FFFFFF'
      V_SERVER_PORT_3: ${JWIZARD_CORE_INSTANCE_1_PORT}
      V_SHARDS_PER_PROCESS_3: 2
      V_SHARD_OVERALL_MAX_3: 2
      V_REST_API_TOKEN_3: ${JWIZARD_REST_API_TOKEN}
      V_XMS_JAVA_3: 2048m
      V_XMX_JAVA_3: 2048m
      # core-instance/1
      V_JDA_SECRET_4: ${JWIZARD_JDA_SECRET_2_INSTANCE}
      V_JDA_INSTANCE_PREFIX_4: 2
      V_JDA_PRIMARY_COLOR_4: '#000000'
      V_SERVER_PORT_4: ${JWIZARD_CORE_INSTANCE_2_PORT}
      V_SHARDS_PER_PROCESS_4: 2
      V_SHARD_OVERALL_MAX_4: 2
      V_REST_API_TOKEN_4: ${JWIZARD_REST_API_TOKEN}
      V_XMS_JAVA_4: 2048m
      V_XMX_JAVA_4: 2048m
      # audio-node/0
      V_NAME_5: AUDIO-QUEUED-NODE-1
      V_REGION_GROUP_5: EUROPE
      V_PASSWORD_5: ${JWIZARD_AUDIO_NODE_TOKEN}
      V_GATEWAY_HOST_5: localhost:${JWIZARD_AUDIO_NODE_1_PORT}
      V_SECURE_5: false
      V_NODE_POOL_5: QUEUED
      V_ACTIVE_5: true
      # audio-node/1
      V_NAME_6: AUDIO-CONTINUOUS-NODE-1
      V_REGION_GROUP_6: EUROPE
      V_PASSWORD_6: ${JWIZARD_AUDIO_NODE_TOKEN}
      V_GATEWAY_HOST_6: localhost:${JWIZARD_AUDIO_NODE_2_PORT}
      V_SECURE_6: false
      V_NODE_POOL_6: CONTINUOUS
      V_ACTIVE_6: true
    cap_add:
      - IPC_LOCK
    networks:
      - jwizard-network

  jwizard-mysql-db:
    container_name: jwizard-mysql-db
    image: mysql:8.0.32
    ports:
      - '${JWIZARD_MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${JWIZARD_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${JWIZARD_MYSQL_DB_NAME}
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
      - ./.volumes/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p${JWIZARD_MYSQL_PASSWORD}"
    networks:
      - jwizard-network

  jwizard-audio-node-1:
    container_name: jwizard-audio-node-1
    image: ghcr.io/lavalink-devs/lavalink:latest
    user: root
    ports:
      - '${JWIZARD_AUDIO_NODE_1_PORT}:${JWIZARD_AUDIO_NODE_1_PORT}'
    environment:
      _JAVA_OPTIONS: -Xmx1G
      SERVER_PORT: ${JWIZARD_AUDIO_NODE_1_PORT}
      # plugins
      LAVALINK_PLUGINS_0_DEPENDENCY: dev.lavalink.youtube:youtube-plugin:${JWIZARD_AUDIO_YT_SOURCE_VERSION}
      # server
      LAVALINK_SERVER_PASSWORD: ${JWIZARD_AUDIO_NODE_TOKEN}
      LAVALINK_SERVER_SOURCES_YOUTUBE: false
      # filters
      LAVALINK_SERVER_FILTERS_VOLUME: true
      LAVALINK_SERVER_BUFFER_DURATION_MS: 400
      LAVALINK_SERVER_FRAME_BUFFER_DURATION_MS: 5000
      LAVALINK_SERVER_OPUS_ENCODING_QUALITY: 10
      LAVALINK_SERVER_RESAMPLING_QUALITY: MEDIUM
      LAVALINK_SERVER_TRACK_STUCK_THRESHOLD_MS: 10000
      LAVALINK_SERVER_USE_SEEK_GHOSTING: true
      # logging
      LOGGING_REQUEST_ENABLED: true
      LOGGING_REQUEST_INCLUDE_CLIENT_INFO: true
      LOGGING_REQUEST_INCLUDE_HEADERS: false
      LOGGING_REQUEST_INCLUDE_QUERY_STRING: true
      LOGGING_REQUEST_INCLUDE_PAYLOAD: true
      LOGGING_REQUEST_MAX_PAYLOAD_LENGTH: 10000
      # logging level
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_LAVALINK: DEBUG
      LOGGING_LEVEL_LAVALINK_SERVER_IO_SOCKETCONTEXT: TRACE
      LOGGING_LEVEL_COM_SEDMELLUQ_DISCORD_LAVAPLAYER_TOOLS_EXCEPTIONTOOLS: DEBUG
      LOGGING_LEVEL_MOE_KYOKOBOT_KOE: DEBUG
      # yt plugin
      PLUGINS_YOUTUBE_ENABLED: true
      PLUGINS_YOUTUBE_POT_TOKEN: ${JWIZARD_AUDIO_YT_PO_TOKEN}
      PLUGINS_YOUTUBE_POT_VISITOR_DATA: ${JWIZARD_AUDIO_YT_PO_VISITOR_DATA}
      PLUGINS_YOUTUBE_ALLOW_SEARCH: true
      PLUGINS_YOUTUBE_ALLOW_DIRECT_VIDEO_IDS: true
      PLUGINS_YOUTUBE_ALLOW_DIRECT_PLAYLIST_IDS: true
      PLUGINS_YOUTUBE_CLIENTS_0: MUSIC
      PLUGINS_YOUTUBE_CLIENTS_1: ANDROID_TESTSUITE
      PLUGINS_YOUTUBE_CLIENTS_2: WEB
      PLUGINS_YOUTUBE_CLIENTS_3: TVHTML5EMBEDDED
    volumes:
      - ./.volumes/lavalink/lavalink-1-volume/plugins:/opt/Lavalink/plugins/
    networks:
      - jwizard-network

  jwizard-audio-node-2:
    container_name: jwizard-audio-node-2
    image: ghcr.io/lavalink-devs/lavalink:latest
    user: root
    ports:
      - '${JWIZARD_AUDIO_NODE_2_PORT}:${JWIZARD_AUDIO_NODE_2_PORT}'
    environment:
      _JAVA_OPTIONS: -Xmx1G
      SERVER_PORT: ${JWIZARD_AUDIO_NODE_2_PORT}
      # server
      LAVALINK_SERVER_PASSWORD: ${JWIZARD_AUDIO_NODE_TOKEN}
      LAVALINK_SERVER_SOURCES_YOUTUBE: false
      # filters
      LAVALINK_SERVER_FILTERS_VOLUME: true
      LAVALINK_SERVER_BUFFER_DURATION_MS: 400
      LAVALINK_SERVER_FRAME_BUFFER_DURATION_MS: 5000
      LAVALINK_SERVER_OPUS_ENCODING_QUALITY: 10
      LAVALINK_SERVER_RESAMPLING_QUALITY: MEDIUM
      LAVALINK_SERVER_TRACK_STUCK_THRESHOLD_MS: 10000
      LAVALINK_SERVER_USE_SEEK_GHOSTING: true
      # logging
      LOGGING_REQUEST_ENABLED: true
      LOGGING_REQUEST_INCLUDE_CLIENT_INFO: true
      LOGGING_REQUEST_INCLUDE_HEADERS: false
      LOGGING_REQUEST_INCLUDE_QUERY_STRING: true
      LOGGING_REQUEST_INCLUDE_PAYLOAD: true
      LOGGING_REQUEST_MAX_PAYLOAD_LENGTH: 10000
      # logging level
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_LAVALINK: DEBUG
      LOGGING_LEVEL_LAVALINK_SERVER_IO_SOCKETCONTEXT: TRACE
      LOGGING_LEVEL_COM_SEDMELLUQ_DISCORD_LAVAPLAYER_TOOLS_EXCEPTIONTOOLS: DEBUG
      LOGGING_LEVEL_MOE_KYOKOBOT_KOE: DEBUG
    volumes:
      - ./.volumes/lavalink/lavalink-2-volume/plugins:/opt/Lavalink/plugins/
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge
